apiVersion: v1
kind: PersistentVolume
metadata:
  name: dnetweb-pv
  labels:
    name: dnetweb # name can be anything
spec:
  storageClassName: dnetweb # same storage class as pvc
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.9.2 # NFS server IP address 
    path: "/Public/k8s_storage/dnetweb/"   # NFS share location 
