apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dnetweb-pvc
spec:
  storageClassName: dnetweb
  accessModes:
    - ReadWriteMany #  must be the same as PersistentVolume
  resources:
    requests:
      storage: 5Gi